name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # schedule:
  #   - cron: '0 23 * * *' # chạy hàng ngày lúc 06:00 giờ Việt Nam (23:00 UTC hôm trước)
jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright tests
      env:
        PLAYWRIGHT_WORKERS: ${{ vars.PLAYWRIGHT_WORKERS || 1 }}
        TEST_USER_0_EMAIL: ${{ secrets.TEST_USER_0_EMAIL }}
        TEST_USER_0_PASSWORD: ${{ secrets.TEST_USER_0_PASSWORD }}
        TEST_USER_1_EMAIL: ${{ secrets.TEST_USER_1_EMAIL }}
        TEST_USER_1_PASSWORD: ${{ secrets.TEST_USER_1_PASSWORD }}
        TEST_USER_2_EMAIL: ${{ secrets.TEST_USER_2_EMAIL }}
        TEST_USER_2_PASSWORD: ${{ secrets.TEST_USER_2_PASSWORD }}
        TEST_USER_3_EMAIL: ${{ secrets.TEST_USER_3_EMAIL }}
        TEST_USER_3_PASSWORD: ${{ secrets.TEST_USER_3_PASSWORD }}
        TEST_USER_4_EMAIL: ${{ secrets.TEST_USER_4_EMAIL }}
        TEST_USER_4_PASSWORD: ${{ secrets.TEST_USER_4_PASSWORD }}
        TEST_USER_5_EMAIL: ${{ secrets.TEST_USER_5_EMAIL }}
        TEST_USER_5_PASSWORD: ${{ secrets.TEST_USER_5_PASSWORD }}
      run: npx playwright test --grep @Regression --workers=$PLAYWRIGHT_WORKERS
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "Playwright CI result: ${{ job.status }}"
        body: |
          Workflow: ${{ github.workflow }}
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }}
          Commit: ${{ github.sha }}
          Status: ${{ job.status }}
          Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        to: ${{ secrets.EMAIL_TO }}
        from: ${{ secrets.EMAIL_FROM }}
